call ppm install net-telnet.ppd
call ppm install yaml.ppd
call ppm install Win32api-Registry.ppd
call ppm install Win32-TieRegistry.ppd
call ppm install File-HomeDir-0.64.ppd
call ppm install AppConfig-1.63.ppd
call ppm install Text-Balanced-1.95.ppd
call ppm install Class-Base-0.03.ppd
call ppm install Class-Data-Inheritable-0.06.ppd
call ppm install Class-MakeMethods-1.009.ppd
call ppm install Parse-RecDescent.ppd
call ppm install Log-Log4perl.ppd
call ppm install Template-Toolkit.ppd
call ppm install SQL-Translator.ppd
