echo Initializing schema...
call mysql.exe -u root -p < %INSTALL_DIR%\Creates.sql
echo Installing stored procedures
call mysql.exe -u root -p < %INSTALL_DIR%\Procedures.sql
echo Importing starter data...
call mysql.exe -u root -p -D DAD < %INSTALL_DIR%\Starter_Data.sql