<?php
//This file is used by AdminMenu.php functions to automatically generate
//and insert new option IDs and names.  PLEASE DO NOT CLOSE WITH A CLOSING
//PHP TAG!!!

define('OPTIONID_ADDNEWMENU', 25);
define('OPTIONID_CHANGEOWNPASSWORDFORM', 13);
define('OPTIONID_CHANGEUSERDETAILSFORM', 22);
define('OPTIONID_CHANGEUSERROLEFORM', 21);
define('OPTIONID_CREATEUSERFORM', 8);
define('OPTIONID_DELETEUSERFORM', 12);
define('OPTIONID_HELP', -4);
define('OPTIONID_HOME', 1);
define('OPTIONID_LANGPREFSUBMIT', 24);
define('OPTIONID_LOGOUT', 20);
define('OPTIONID_LOGINPAGE', 6);
define('OPTIONID_LOGINUSER', 7);
define('OPTIONID_MENUADMINSELECT', 11);
define('OPTIONID_RESETUSERPASSWORDFORM', 14);
define('OPTIONID_SUBMITNEWOPTION', 26);
define('OPTIONID_JASONS_NUTS', 39);
define('OPTIONID_SUBMIT_MODIFIED_MENU', 40);
define('OPTIONID_FILE_SYSTEM', 42);
define('OPTIONID_FS_DETAIL_SHOW', 44);
define('OPTIONID_FS_DETAIL_EDIT', 46);
define('OPTIONID_FILE_SYSTEM_HISTORY', 49);
define('OPTIONID_SYSTEM_LOGS', 50);
define('OPTIONID_NEW_FILE_SYSTEM_ENTRIES', 52);
define('OPTIONID_PUBLIC_FOLDER<BOLD>', 53);
define('OPTIONID_NEW_PUBLIC_FOLDER_ENTRIES', 54);
define('OPTIONID_PUBLIC_FOLDER_HISTORY', 55);
define('OPTIONID_PF_DETAIL_EDIT', 56);
define('OPTIONID_LOG_ANALYSIS', 57);
define('OPTIONID_EXISTING_QUERIES', 58);
define('OPTIONID_QUERY_BUILDER', 59);
define('OPTIONID_SQL_QUERY', 60);
define('OPTIONID_JOBS', 61);
define('OPTIONID_FILE_AUDIT_SEARCH', 62);
define('OPTIONID_SQL_PROCESS_LIST', 63);
define('OPTIONID_SYSTEMS', 64);
define('OPTIONID_ALERT_GROUP_ADMIN', 65);
define('OPTIONID_JUNK', 66);
define('OPTIONID_ALERT_USER_ADMIN', 67);
define('OPTIONID_COMPUTER_GROUPS_ADMIN', 68);
define('OPTIONID_ALERT_ADMIN', 69);
